// flow-typed signature: 056bacd0a1064da066296ab47a979058
// flow-typed version: <<STUB>>/@paypal/messaging-components_v^1.12.1/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@paypal/messaging-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@paypal/messaging-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@paypal/messaging-components/__sdk__' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/merchant' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/messaging' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/smart-credit-modal' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/merchant@1.12.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/messaging@1.12.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-modal@1.12.1' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/globals' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/interface/messages' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/legacy' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/legacy/map' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/legacy/toNewPipeline' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/DE' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/DE/logos' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/DE/mutations' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/DE/mutations/inst_any_eqz' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/DE/mutations/inst_any_gtz' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/DE/mutations/mediaQueries' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/DE/mutations/palaq_any_eqz' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/DE/mutations/palaq_any_gtz' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/DE/styles/flex' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/DE/styles' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/DE/styles/text' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/DE/validOptions' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/GB' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/GB/logos' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/GB/mutations' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/GB/mutations/mediaQueries' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/GB/mutations/pl' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/GB/mutations/plq' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/GB/styles/flex' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/GB/styles' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/GB/styles/text' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/GB/validOptions' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/logos' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/mutations/common' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/mutations/ezp_any_eqz' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/mutations/ezp_any_gtz' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/mutations' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/mutations/mediaQueries' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/mutations/ni_non-us' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/mutations/ni' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/mutations/niq_non-us' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/mutations/niq' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/mutations/pala_multi_eqz' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/mutations/pala_multi_gtz' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/mutations/pala_single_eqz' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/mutations/pala_single_gtz' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/styles/flex' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/styles' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/styles/text' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/locale/US/validOptions' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/components/Modal/component' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/components/Modal/containerTemplate' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/components/Modal' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/components/Modal/viewportHijack' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/controllers/render' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Banner' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Banner/types' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Banner/validateOptions' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Container/events' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Container' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Container/insertMarkup' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Container/setSize' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Container/stats' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Template' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Template/styles/custom' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Template/styles/flex' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Template/styles' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Template/styles/legacyHtml' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/models/Template/styles/text' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/services/banner/customTemplate' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/services/banner' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/services/banner/public.key' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/services/logger' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/messages/services/logger/sendBeacon' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/content/Content' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/content/DE/INST' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/content/GB/PL' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/content/US/EZP' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/content/US/NI' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/lib/context' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/lib/hooks/applyNow' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/lib/hooks/calculator' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/lib/hooks/helpers' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/lib/hooks' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/lib/hooks/scroll' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/lib/hooks/transitionState' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/lib/scroll' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/lib/transition' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/Modal' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Accordion' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Button' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Calculator/DE/Calculator' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Calculator/DE/Disclaimer' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Calculator/DE/TermsTable' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Calculator' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Calculator/US/Calculator' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Calculator/US/TermsTable' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Carousel' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Container' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Header' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Icon' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Overlay' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/parts/Tabs' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/modal/styles' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/elements' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/experimentation' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/fonts' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/functional' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/global' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/miscellaneous' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/objects' {
  declare module.exports: any;
}

declare module '@paypal/messaging-components/src/utils/sdk' {
  declare module.exports: any;
}

// Filename aliases
declare module '@paypal/messaging-components/__sdk__.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/__sdk__'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/merchant.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/merchant'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/messaging.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/messaging'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/smart-credit-modal.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/smart-credit-modal'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/merchant@1.12.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/versioned/merchant@1.12.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/messaging@1.12.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/versioned/messaging@1.12.1'>;
}
declare module '@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-modal@1.12.1.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/dist/bizcomponents/js/versioned/smart-credit-modal@1.12.1'>;
}
declare module '@paypal/messaging-components/globals.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/globals'>;
}
declare module '@paypal/messaging-components/src/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src'>;
}
declare module '@paypal/messaging-components/src/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src'>;
}
declare module '@paypal/messaging-components/src/interface/messages.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/interface/messages'>;
}
declare module '@paypal/messaging-components/src/legacy/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/legacy'>;
}
declare module '@paypal/messaging-components/src/legacy/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/legacy'>;
}
declare module '@paypal/messaging-components/src/legacy/map.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/legacy/map'>;
}
declare module '@paypal/messaging-components/src/legacy/toNewPipeline.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/legacy/toNewPipeline'>;
}
declare module '@paypal/messaging-components/src/locale/DE/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE'>;
}
declare module '@paypal/messaging-components/src/locale/DE/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE'>;
}
declare module '@paypal/messaging-components/src/locale/DE/logos.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/logos'>;
}
declare module '@paypal/messaging-components/src/locale/DE/mutations/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/mutations'>;
}
declare module '@paypal/messaging-components/src/locale/DE/mutations/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/mutations'>;
}
declare module '@paypal/messaging-components/src/locale/DE/mutations/inst_any_eqz.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/mutations/inst_any_eqz'>;
}
declare module '@paypal/messaging-components/src/locale/DE/mutations/inst_any_gtz.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/mutations/inst_any_gtz'>;
}
declare module '@paypal/messaging-components/src/locale/DE/mutations/mediaQueries.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/mutations/mediaQueries'>;
}
declare module '@paypal/messaging-components/src/locale/DE/mutations/palaq_any_eqz.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/mutations/palaq_any_eqz'>;
}
declare module '@paypal/messaging-components/src/locale/DE/mutations/palaq_any_gtz.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/mutations/palaq_any_gtz'>;
}
declare module '@paypal/messaging-components/src/locale/DE/styles/flex/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/styles/flex'>;
}
declare module '@paypal/messaging-components/src/locale/DE/styles/flex/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/styles/flex'>;
}
declare module '@paypal/messaging-components/src/locale/DE/styles/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/styles'>;
}
declare module '@paypal/messaging-components/src/locale/DE/styles/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/styles'>;
}
declare module '@paypal/messaging-components/src/locale/DE/styles/text/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/styles/text'>;
}
declare module '@paypal/messaging-components/src/locale/DE/styles/text/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/styles/text'>;
}
declare module '@paypal/messaging-components/src/locale/DE/validOptions.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/DE/validOptions'>;
}
declare module '@paypal/messaging-components/src/locale/GB/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB'>;
}
declare module '@paypal/messaging-components/src/locale/GB/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB'>;
}
declare module '@paypal/messaging-components/src/locale/GB/logos.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB/logos'>;
}
declare module '@paypal/messaging-components/src/locale/GB/mutations/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB/mutations'>;
}
declare module '@paypal/messaging-components/src/locale/GB/mutations/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB/mutations'>;
}
declare module '@paypal/messaging-components/src/locale/GB/mutations/mediaQueries.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB/mutations/mediaQueries'>;
}
declare module '@paypal/messaging-components/src/locale/GB/mutations/pl.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB/mutations/pl'>;
}
declare module '@paypal/messaging-components/src/locale/GB/mutations/plq.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB/mutations/plq'>;
}
declare module '@paypal/messaging-components/src/locale/GB/styles/flex/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB/styles/flex'>;
}
declare module '@paypal/messaging-components/src/locale/GB/styles/flex/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB/styles/flex'>;
}
declare module '@paypal/messaging-components/src/locale/GB/styles/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB/styles'>;
}
declare module '@paypal/messaging-components/src/locale/GB/styles/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB/styles'>;
}
declare module '@paypal/messaging-components/src/locale/GB/styles/text/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB/styles/text'>;
}
declare module '@paypal/messaging-components/src/locale/GB/styles/text/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB/styles/text'>;
}
declare module '@paypal/messaging-components/src/locale/GB/validOptions.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/GB/validOptions'>;
}
declare module '@paypal/messaging-components/src/locale/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale'>;
}
declare module '@paypal/messaging-components/src/locale/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale'>;
}
declare module '@paypal/messaging-components/src/locale/US/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US'>;
}
declare module '@paypal/messaging-components/src/locale/US/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US'>;
}
declare module '@paypal/messaging-components/src/locale/US/logos.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/logos'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/common.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations/common'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/ezp_any_eqz.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations/ezp_any_eqz'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/ezp_any_gtz.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations/ezp_any_gtz'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/mediaQueries.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations/mediaQueries'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/ni_non-us.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations/ni_non-us'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/ni.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations/ni'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/niq_non-us.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations/niq_non-us'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/niq.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations/niq'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/pala_multi_eqz.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations/pala_multi_eqz'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/pala_multi_gtz.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations/pala_multi_gtz'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/pala_single_eqz.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations/pala_single_eqz'>;
}
declare module '@paypal/messaging-components/src/locale/US/mutations/pala_single_gtz.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/mutations/pala_single_gtz'>;
}
declare module '@paypal/messaging-components/src/locale/US/styles/flex/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/styles/flex'>;
}
declare module '@paypal/messaging-components/src/locale/US/styles/flex/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/styles/flex'>;
}
declare module '@paypal/messaging-components/src/locale/US/styles/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/styles'>;
}
declare module '@paypal/messaging-components/src/locale/US/styles/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/styles'>;
}
declare module '@paypal/messaging-components/src/locale/US/styles/text/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/styles/text'>;
}
declare module '@paypal/messaging-components/src/locale/US/styles/text/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/styles/text'>;
}
declare module '@paypal/messaging-components/src/locale/US/validOptions.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/locale/US/validOptions'>;
}
declare module '@paypal/messaging-components/src/messages/components/Modal/component.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/components/Modal/component'>;
}
declare module '@paypal/messaging-components/src/messages/components/Modal/containerTemplate.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/components/Modal/containerTemplate'>;
}
declare module '@paypal/messaging-components/src/messages/components/Modal/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/components/Modal'>;
}
declare module '@paypal/messaging-components/src/messages/components/Modal/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/components/Modal'>;
}
declare module '@paypal/messaging-components/src/messages/components/Modal/viewportHijack.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/components/Modal/viewportHijack'>;
}
declare module '@paypal/messaging-components/src/messages/controllers/render.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/controllers/render'>;
}
declare module '@paypal/messaging-components/src/messages/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages'>;
}
declare module '@paypal/messaging-components/src/messages/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages'>;
}
declare module '@paypal/messaging-components/src/messages/models/Banner/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Banner'>;
}
declare module '@paypal/messaging-components/src/messages/models/Banner/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Banner'>;
}
declare module '@paypal/messaging-components/src/messages/models/Banner/types.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Banner/types'>;
}
declare module '@paypal/messaging-components/src/messages/models/Banner/validateOptions.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Banner/validateOptions'>;
}
declare module '@paypal/messaging-components/src/messages/models/Container/events.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Container/events'>;
}
declare module '@paypal/messaging-components/src/messages/models/Container/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Container'>;
}
declare module '@paypal/messaging-components/src/messages/models/Container/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Container'>;
}
declare module '@paypal/messaging-components/src/messages/models/Container/insertMarkup.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Container/insertMarkup'>;
}
declare module '@paypal/messaging-components/src/messages/models/Container/setSize.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Container/setSize'>;
}
declare module '@paypal/messaging-components/src/messages/models/Container/stats.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Container/stats'>;
}
declare module '@paypal/messaging-components/src/messages/models/Template/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Template'>;
}
declare module '@paypal/messaging-components/src/messages/models/Template/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Template'>;
}
declare module '@paypal/messaging-components/src/messages/models/Template/styles/custom/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Template/styles/custom'>;
}
declare module '@paypal/messaging-components/src/messages/models/Template/styles/custom/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Template/styles/custom'>;
}
declare module '@paypal/messaging-components/src/messages/models/Template/styles/flex/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Template/styles/flex'>;
}
declare module '@paypal/messaging-components/src/messages/models/Template/styles/flex/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Template/styles/flex'>;
}
declare module '@paypal/messaging-components/src/messages/models/Template/styles/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Template/styles'>;
}
declare module '@paypal/messaging-components/src/messages/models/Template/styles/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Template/styles'>;
}
declare module '@paypal/messaging-components/src/messages/models/Template/styles/legacyHtml/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Template/styles/legacyHtml'>;
}
declare module '@paypal/messaging-components/src/messages/models/Template/styles/legacyHtml/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Template/styles/legacyHtml'>;
}
declare module '@paypal/messaging-components/src/messages/models/Template/styles/text/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Template/styles/text'>;
}
declare module '@paypal/messaging-components/src/messages/models/Template/styles/text/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/models/Template/styles/text'>;
}
declare module '@paypal/messaging-components/src/messages/services/banner/customTemplate.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/services/banner/customTemplate'>;
}
declare module '@paypal/messaging-components/src/messages/services/banner/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/services/banner'>;
}
declare module '@paypal/messaging-components/src/messages/services/banner/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/services/banner'>;
}
declare module '@paypal/messaging-components/src/messages/services/banner/public.key.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/services/banner/public.key'>;
}
declare module '@paypal/messaging-components/src/messages/services/logger/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/services/logger'>;
}
declare module '@paypal/messaging-components/src/messages/services/logger/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/services/logger'>;
}
declare module '@paypal/messaging-components/src/messages/services/logger/sendBeacon.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/messages/services/logger/sendBeacon'>;
}
declare module '@paypal/messaging-components/src/modal/content/Content.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/content/Content'>;
}
declare module '@paypal/messaging-components/src/modal/content/DE/INST.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/content/DE/INST'>;
}
declare module '@paypal/messaging-components/src/modal/content/GB/PL.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/content/GB/PL'>;
}
declare module '@paypal/messaging-components/src/modal/content/US/EZP.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/content/US/EZP'>;
}
declare module '@paypal/messaging-components/src/modal/content/US/NI.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/content/US/NI'>;
}
declare module '@paypal/messaging-components/src/modal/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal'>;
}
declare module '@paypal/messaging-components/src/modal/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal'>;
}
declare module '@paypal/messaging-components/src/modal/lib/context.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/lib/context'>;
}
declare module '@paypal/messaging-components/src/modal/lib/hooks/applyNow.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/lib/hooks/applyNow'>;
}
declare module '@paypal/messaging-components/src/modal/lib/hooks/calculator.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/lib/hooks/calculator'>;
}
declare module '@paypal/messaging-components/src/modal/lib/hooks/helpers.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/lib/hooks/helpers'>;
}
declare module '@paypal/messaging-components/src/modal/lib/hooks/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/lib/hooks'>;
}
declare module '@paypal/messaging-components/src/modal/lib/hooks/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/lib/hooks'>;
}
declare module '@paypal/messaging-components/src/modal/lib/hooks/scroll.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/lib/hooks/scroll'>;
}
declare module '@paypal/messaging-components/src/modal/lib/hooks/transitionState.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/lib/hooks/transitionState'>;
}
declare module '@paypal/messaging-components/src/modal/lib/scroll.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/lib/scroll'>;
}
declare module '@paypal/messaging-components/src/modal/lib/transition.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/lib/transition'>;
}
declare module '@paypal/messaging-components/src/modal/Modal.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/Modal'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Accordion.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Accordion'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Button.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Button'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Calculator/DE/Calculator.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Calculator/DE/Calculator'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Calculator/DE/Disclaimer.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Calculator/DE/Disclaimer'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Calculator/DE/TermsTable.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Calculator/DE/TermsTable'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Calculator/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Calculator'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Calculator/index.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Calculator'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Calculator/US/Calculator.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Calculator/US/Calculator'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Calculator/US/TermsTable.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Calculator/US/TermsTable'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Carousel.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Carousel'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Container.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Container'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Header.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Header'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Icon.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Icon'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Overlay.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Overlay'>;
}
declare module '@paypal/messaging-components/src/modal/parts/Tabs.jsx' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/parts/Tabs'>;
}
declare module '@paypal/messaging-components/src/modal/styles/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/styles'>;
}
declare module '@paypal/messaging-components/src/modal/styles/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/modal/styles'>;
}
declare module '@paypal/messaging-components/src/utils/elements.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/elements'>;
}
declare module '@paypal/messaging-components/src/utils/experimentation.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/experimentation'>;
}
declare module '@paypal/messaging-components/src/utils/fonts.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/fonts'>;
}
declare module '@paypal/messaging-components/src/utils/functional.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/functional'>;
}
declare module '@paypal/messaging-components/src/utils/global.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/global'>;
}
declare module '@paypal/messaging-components/src/utils/index' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils'>;
}
declare module '@paypal/messaging-components/src/utils/index.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils'>;
}
declare module '@paypal/messaging-components/src/utils/miscellaneous.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/miscellaneous'>;
}
declare module '@paypal/messaging-components/src/utils/objects.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/objects'>;
}
declare module '@paypal/messaging-components/src/utils/sdk.js' {
  declare module.exports: $Exports<'@paypal/messaging-components/src/utils/sdk'>;
}
